name: Aflot TEST deploy
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull remote origin
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/aflot/nuxt
          git pull origin master
          npm run build
          pm2 kill
          pm2 start ecosystem.config.mjs
          pm2 save
